//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OngTV.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_SCINTILLA_FINDDLGORD        101
#define IDD_SCINTILLA_REPLACEDLGORD     102
#define IDD_REL_NOTES                   103
#define IDR_MAINFRAME                   127
#define IDR_MAINFRAME_OPERATOR          128
#define IDR_MAINFRAME_ENGINEER          129
#define IDB_IL_PROCEXPLVIEW             130
#define IDB_IL_PROCVIEW                 131
#define IDB_IL_SYMVIEW                  132
#define IDB_SPLASHADEVIEW               141
#define IDI_ICON1                       145
#define IDC_TREE_PROC                   150
#define IDR_DINA                        152
#define IDI_PERT_STOPPED                155
#define IDI_PERT_ON_WATCHED             156
#define IDI_PERT_ARMED                  157
#define IDI_PERT_INVALID_CFG            158
#define IDI_SEQTST_STOPPED              160
#define IDR_SPYDLG                      160
#define IDI_SEQTST_STOPPED_ON_ERROR     161
#define IDI_SEQTST_BUSY1                162
#define IDI_SEQTST_BUSY2                163
#define IDI_SEQTST_BUSY3                164
#define IDI_SEQTST_BUSY4                165
#define IDI_FILEMGRDLG_DIR              166
#define IDI_FILEMGRDLG_FILE             167
#define IDR_SPYDLG_READONLYFILE         172
#define IDS_SCINTILLA_DEFAULT_PRINT_HEADER 180
#define IDS_SCINTILLA_DEFAULT_PRINT_FOOTER 181
#define IDS_RESTART                     200
#define IDR_DASHBOARDTYPE_RECORDS       998
#define IDR_HTMLDASHBOARDTYPE           999
#define IDR_DASHBOARDTYPE               1000
#define IDC_TREE_SYM                    1001
#define IDR_LUATYPE                     1002
#define IDR_MEM                         1004
#define IDR_EVT                         1005
#define IDR_PERTCTRL                    1006
#define IDR_PERTFILMS                   1007
#define IDR_SEQTST                      1008
#define IDR_SPY                         1009
#define IDD_MEMDLG                      1019
#define IDR_MEMDLG                      1020
#define ID_MEMDLG_DUMP                  1021
#define ID_MEMDLG_COMBOPROC             1022
#define IDC_MEMDLG_MEMADDR              1023
#define IDC_MEMDLG_MEMSIZE              1024
#define ID_MEMDLG_FORMAT_DUMP_BYTE      1025
#define ID_MEMDLG_FORMAT_DUMP_SHORT     1026
#define ID_MEMDLG_FORMAT_DUMP_LONG      1027
#define IDC_MEMDLG_MEMWATCH             1028
#define IDD_EVTDLG                      1039
#define IDR_EVTDLG                      1040
#define IDR_EVTDLG_OPERATOR             1041
#define IDR_EVTDLG_READONLYFILE         1042
#define ID_EVTDLG_READ_EVENTS           1043
#define ID_EVTDLG_CLEAR_EVENTS          1044
#define ID_EVTDLG_SAVE_EVENTS           1045
#define ID_EVTDLG_GET_SET_COMMENT       1046
#define ID_EVTDLG_EXPORTTOCSV           1047
#define ID_EVTDLG_COMBOTYPE             1048
#define ID_EVTDLG_COMBOEVENT            1049
#define ID_EVTDLG_EDITNB_RECORDS        1050
#define IDC_EVTDLG_DESCRIPTION          1051
#define IDC_EVTDLG_LISTCONTEXTS         1052
#define IDC_EVTDLG_LISTEVENTS           1053
#define IDD_SELPROCDLG                  1055
#define IDC_SELPROCDLG_PROC             1056
#define IDD_SELPERTDLG                  1057
#define IDC_SELPERTDLG_PROC             1058
#define IDD_INITMEMSYMDLG               1060
#define IDR_INITMEMSYMDLG               1061
#define ID_INITMEMSYMDLG_DO             1062
#define ID_INITMEMSYMDLG_REDO           1063
#define ID_INITMEMSYMDLG_DO_NEXT_STEP   1064
#define IDC_INITMEMSYMDLG_STATUS        1065
#define IDD_CHANGEMODEDLG               1070
#define ID_MODE_APPLY                   1071
#define IDC_CURR_MODE                   1072
#define IDC_NEW_MODE                    1073
#define IDD_CLOCKDLG                    1080
#define IDC_DATETIMEPICKER_READDATE     1081
#define IDC_DATETIMEPICKER_READTIME     1082
#define IDC_DATETIMEPICKER_WRITEDATE    1083
#define IDC_DATETIMEPICKER_WRITETIME    1084
#define ID_UPDATE_TIME                  1085
#define IDD_PERTCTRLDLG                 1090
#define IDR_PERTCTRLDLG                 1091
#define ID_PERTCTRLDLG_STOP_PERT        1092
#define ID_PERTCTRLDLG_WATCH            1093
#define ID_PERTCTRLDLG_ARM              1094
#define ID_PERTCTRLDLG_RESTORE_FACTORY_CFG 1095
#define ID_PERTCTRLDLG_UPLOAD_NEW_CFG   1096
#define ID_PERTCTRLDLG_GET_CURRENT_CFG  1097
#define ID_PERTCTRLDLG_DOWNLOAD_FILMS   1098
#define IDC_PERTCTRLDLG_ICON_STATE      1099
#define IDC_PERTCTRLDLG_STATE           1100
#define IDC_PERTCTRLDLG_CFG_TYPE        1101
#define IDC_PERTCTRLDLG_PERCENT         1102
#define IDC_PERTCTRLDLG_FILLED_FILMS    1103
#define IDD_PERTFILMSDLG                1200
#define IDR_PERTFILMSDLG                1201
#define ID_PERTFILMSDLG_SAVE            1202
#define ID_PERTFILMSDLG_GET_SET_COMMENT 1203
#define ID_PERTFILMSDLG_LOAD_LAYOUT     1204
#define ID_PERTFILMSDLG_SAVE_LAYOUT     1205
#define ID_PERTFILMSDLG_EXPORTTOCSV     1206
#define ID_PERTFILMSDLG_SEL_FILM        1207
#define ID_PERTFILMSDLG_SHOW_LIST       1211
#define ID_PERTFILMSDLG_SHOW_SCOPE1     1212
#define ID_PERTFILMSDLG_SHOW_SCOPE2     1213
#define ID_PERTFILMSDLG_SHOW_SCOPE3     1214
#define ID_PERTFILMSDLG_SHOW_SCOPE4     1215
#define ID_PERTFILMSDLG_LINK_SCOPES     1216
#define ID_PERTFILMSDLG_CONF_SCOPES     1217
#define IDC_PERTFILMSDLG_PER            1218
#define IDC_PERTFILMSDLG_VARS_LIST      1220
#define IDC_PERTFILMSDLG_SCOPES_PANEL   1221
#define ID_PERTFILMSDLG_COMBOFILM       1222
#define IDD_SELPERTFILMDLG              1230
#define IDC_SELPERTFILMDLG_LISTFILMS    1231
#define IDD_PERTFILMSCSVEXPORTOPTIONS_DLG 1240
#define IDC_PERTFILMSCSVEXPORTOPTIONS_ALL 1241
#define IDC_PERTFILMSCSVEXPORTOPTIONS_CURRENT 1242
#define IDC_EDIT_VALUE                  1300
#define IDC_STATIC_VALUE                1301
#define IDC_LIST_VALUES                 1302
#define IDC_P0                          1320
#define IDC_P1                          1321
#define IDC_P2                          1322
#define IDC_P3                          1323
#define IDC_P4                          1324
#define IDD_GET_VAL                     1330
#define IDD_GET_VAL_FROM_LIST           1331
#define IDD_GET_VAL_ENUM                1332
#define IDD_GET_PARAM                   1333
#define IDD_GET_PWD                     1334
#define IDD_GET_HOST_FILE_NAME          1335
#define IDC_REAL_CONNECION              1336
#define IDC_PSEUDO_CONNECION            1337
#define IDC_NONE_CONNECION              1338
#define IDD_DASHBOARDDLG                1400
#define IDR_DASHBOARDDLG                1401
#define IDR_DASHBOARDDLG_READONLYFILE   1402
#define ID_DASHBOARDDLG_GET_COMMENT     1403
#define ID_DASHBOARDDLG_SAVE            1404
#define ID_DASHBOARDDLG_SAVEAS          1405
#define ID_DASHBOARDDLG_SAVERECORDS     1406
#define ID_DASHBOARDDLG_START_STOP_REFRESH 1407
#define ID_DASHBOARDDLG_REMOVE_SYMBOL   1408
#define ID_DASHBOARDDLG_REMOVE_ALL_SYMBOLS 1409
#define ID_DASHBOARDDLG_FREEZE          1410
#define ID_DASHBOARDDLG_UNFREEZE        1411
#define ID_DASHBOARDDLG_SHOW_LIST       1412
#define ID_DASHBOARDDLG_SHOW_SCOPE1     1413
#define ID_DASHBOARDDLG_SHOW_SCOPE2     1414
#define ID_DASHBOARDDLG_SHOW_SCOPE3     1415
#define ID_DASHBOARDDLG_SHOW_SCOPE4     1416
#define ID_DASHBOARDDLG_LINK_SCOPES     1417
#define ID_DASHBOARDDLG_CONF_SCOPES     1418
#define IDC_DASHBOARDDLG_PER            1419
#define IDC_DASHBOARDDLG_SYM_LIST       1420
#define IDC_DASHBOARDDLG_SCOPES_PANEL   1421
#define IDR_LUASCRIPT                   1451
#define ID_LUASCRIPT_SAVE               1452
#define ID_LUASCRIPT_SAVEAS             1453
#define ID_LUASCRIPT_RUN                1454
#define ID_LUASCRIPT_TOGGLE_BREAKPOINT  1455
#define ID_LUASCRIPT_STOP               1456
#define ID_LUASCRIPT_BREAK              1457
#define ID_LUASCRIPT_STEP_INTO          1458
#define ID_LUASCRIPT_STEP_OVER          1459
#define ID_LUASCRIPT_STEP_OUT           1460
#define ID_LUASCRIPT_RUN_TO_CURSOR      1461
#define ID_OPTIONS_TOGGLEMARKER         1463
#define ID_OPTIONS_FIND_NEXTMARKER      1464
#define ID_OPTIONS_FIND_PREVMARKER      1465
#define ID_LUASCRIPT_GOTO_LINE          1466
#define ID_LUASCRIPT_CTRL_F3            1467
#define ID_LUASCRIPT_SHIFT_F3           1468
#define ID_LUASCRIPT_CTRL_SPACE         1469
#define ID_LUASCRIPT_CTRL_SHIFT_SPACE   1470
#define IDD_SEQTSTDLG                   1499
#define IDR_SEQTSTDLG                   1500
#define IDR_SEQTSTDLG_OPERATOR          1501
#define IDR_SEQTSTDLG_READONLYFILE      1502
#define ID_SEQTSTDLG_START_SEQ          1503
#define ID_SEQTSTDLG_STOP_SEQ           1504
#define ID_SEQTSTDLG_STEP_BY_STEP       1505
#define ID_SEQTSTDLG_SAVE_TRACES        1506
#define ID_SEQTSTDLG_GET_SET_COMMENT    1507
#define ID_SEQTSTDLG_EXPORTTOCSV        1508
#define ID_SEQTSTDLG_COMBO_SEQ          1509
#define ID_SEQTSTDLG_SHOW_WARNINGS      1510
#define ID_SEQTSTDLG_SHOW_INFORMATIONS  1511
#define IDC_SEQTSTDLG_ICON_STATE        1512
#define IDC_SEQTSTDLG_STATE             1513
#define IDC_SEQTSTDLG_CURR_SEQ          1514
#define IDC_SEQTSTDLG_LIST_STEPS        1515
#define IDC_SEQTSTDLG_LIST_TRACES       1516
#define IDC_SEQTSTDLG_DESC_STEP         1517
#define IDC_SEQTSTDLG_DESC_TRACE        1518
#define IDC_SEQTSTDLG_LISTCONTEXTS      1519
#define IDD_COMMENT                     1600
#define IDC_COMMENT                     1601
#define IDC_LISTPROCESSORS              1602
#define IDC_QUESTION                    1603
#define IDD_SELVERSIONDLG               1610
#define IDC_LISTVERSIONS                1611
#define IDR_PERTCONFIG                  1649
#define IDD_FILEMGRDLG                  1650
#define IDR_FILEMGRDLG                  1651
#define IDD_SPYDLG                      1651
#define ID_FILEMGRDLG_PUT_FILE          1652
#define ID_FILEMGRDLG_GET_FILE          1653
#define ID_FILEMGRDLG_DELETE_FILE       1654
#define ID_FILEMGRDLG_CREATE_DIR        1655
#define ID_FILEMGRDLG_DELETE_DIR        1656
#define IDC_FILEMGRDLG_LISTFILE         1657
#define ID_SPYDLG_READ_SPY              1670
#define ID_SPYDLG_STOP_SPY              1671
#define ID_SPYDLG_SAVE_SPY              1672
#define ID_SPYDLG_GET_SET_COMMENT       1673
#define ID_SPYDLG_EXPORTTOCSV           1674
#define ID_SPYDLG_COMBOINTERFACE        1675
#define ID_SPYDLG_COMBONAME             1676
#define ID_SPYDLG_COMBOSENS             1677
#define ID_SPYDLG_EDITNB_RECORDS        1678
#define IDC_SPYDLG_LISTSPY              1700
#define IDC_SPYDLG_SPYDESCRIPTION       1702
#define IDC_HOST                        1703
#define IDC_LIST_VAR_TERM               1704
#define STR_DLG_CONFIG_PERTURBO_TITLE   1705
#define STR_MAX_TERM_REACHED            1706
#define IDC_ECHAN_APPLI                 1708
#define IDC_ECHAN_INTERNE               1709
#define IDC_PERIODE_ECHAN               1710
#define IDC_NB_ECHAN_MAX_FILM           1711
#define IDC_NB_ECHAN_DECL               1712
#define IDC_LABEL_PERIODE               1713
#define IDC_NB_MAX_FILMS                1714
#define IDC_GESTION_FILM_PILE           1715
#define IDC_TERM_EQ_ARM                 1715
#define IDC_RADIO3                      1716
#define IDC_TERM_EQ_DECL                1716
#define IDC_GESTION_FILM_FILE           1716
#define IDC_SUPPR_TERME_EQ_ARM          1718
#define IDC_MODIF_TERME_EQ_ARM          1719
#define IDC_AJOUT_TERME_EQ_ARM          1720
#define IDC_SUPPR_TERME_EQ_DECL         1721
#define IDC_MODIF_TERME_EQ_DECL         1722
#define IDC_ONGLETS_CONFIG_PERT         1722
#define IDC_BUTTON1                     1723
#define IDC_AJOUT_TERME_EQ_DECL         1723
#define ID_PERTCONFIGDLG_SAVE_AS_CFG    1724
#define ID_PERTCONFIGDLG_SAVE_CFG       1725
#define ID_PERTCONFIGDLG_UPLOAD_CFG     1726
#define IDD_ONGLET_ECHAN_FILM           1727
#define IDD_ONGLET_EQU                  1728
#define IDD_ONGLET_VARLIST              1729
#define IDC_SPIN_NB_MAX_FILM            1730
#define IDD_CREATION_TERME              1731
#define IDC_SPIN_NB_ECHAN_MAX_FILM      1731
#define IDD_PERT_CONFIG                 1732
#define IDB_PERTCONFIGDLG               1733
#define IDS_COLONNE_ACTIV_CREATION_TERM 1734
#define IDC_LISTVAR                     1734
#define IDS_COLONNE_VALEUR_CREATION_TERM 1735
#define IDS_COLONNE_VARIABLE_CREATION_TERM 1736
#define IDS_COLONNE_EQU_ARM             1737
#define IDC_LABEL_FILMS                 1737
#define IDS_COLONNE_EQU_DECL            1738
#define IDC_LABEL_EQUARM                1738
#define IDS_COLONNE_FLAG                1739
#define IDC_LABEL_EQUDECL               1739
#define IDS_COLONNE_VARIABLE            1740
#define IDS_ONGLET_ECHAN_FILM           1741
#define IDS_ONGLET_LIST_VAR             1742
#define IDS_ONGLET_EQU                  1743
#define STR_ET                          1744
#define STR_NON                         1745
#define STR_CONFIG_INCORRECTE           1746
#define IDS_SAVE_CURR_CFG               1747
#define IDS_TITLE_NEW_CFG               1748
#define IDS_ERROR_OPEN_CFG              1749
#define IDS_SEL_PERT_LOADING_CONFIG     1750
#define IDS_TOOL_TIP_EQU                1751
#define IDS_TOOL_TIP_TERM               1752
#define IDS_TYPE_ECHAN_APPLI            1753
#define IDS_TYPE_ECHAN_INTERNE          1754
#define IDS_PERIODE_ECHAN               1755
#define IDS_NB_ECHAN_MAX_FILM           1756
#define IDS_NB_ECHAN_APRES_DECL         1757
#define IDS_NB_MAX_FILM                 1758
#define IDS_ERROR_PROC_NOT_AVAILABLE    1759
#define IDS_CONFIRM_SUPPR               1760
#define IDS_CONFIRM_SUPPR_UNCHECK_SUITE 1761
#define IDS_CONFIRM_UNCHECK             1762
#define IDR_PERT_CONFIG                 1763
#define IDS_EXISTING_TERM               1764
#define IDS_LABEL_APPLI                 1765
#define IDS_LABEL_INTERNE               1766
#define IDS_TOOL_TIP_EQUARM             1767
#define IDS_TOOL_TIP_EQUDECL            1768
#define IDS_TOOL_TIP_FILMS              1769
#define IDC_REGULAR_EXPRESSION          1800
#define STR_VALUE                       2000
#define STR_PROPERTY                    2001
#define STR_NAME                        2002
#define STR_ADDRESS                     2003
#define IDC_ABOUT_VERSION               2003
#define STR_SYMBOL                      2004
#define STR_UNIT                        2005
#define IDC_ABOUT_COMPONENTS            2005
#define STR_CODE                        2006
#define STR_STATUS                      2007
#define STR_DATE_TIME                   2008
#define STR_PROCESSOR                   2009
#define STR_TYPE                        2010
#define STR_FILM_NUM                    2011
#define STR_SAMPLES_NB                  2012
#define STR_ARMING_DATE_TIME            2013
#define STR_ARMING_CAUSE                2014
#define STR_TRIGGERING_DATE_TIME        2015
#define STR_TRIGGERING_CAUSE            2016
#define STR_PERT_CAUSE_EQUATION         2017
#define STR_PERT_CAUSE_MAINTENANCE      2018
#define STR_INTERFACE                   2019
#define STR_TIMESTAMP                   2020
#define STR_INOUT                       2021
#define STR_DATA                        2023
#define IDC_BROWSER                     2024
#define STR_ERROR                       2100
#define STR_ERROR_NOT_SCALAR_SYMBOL     2101
#define STR_ERROR_UNKNOWN_SYMBOL        2102
#define STR_ERROR_UNKNOWN_PROCESSOR     2103
#define STR_ERROR_BAD_VALUE             2104
#define STR_FORBIDDEN                   2105
#define STR_ACK_FAULTS_MSGBOX_TITLE     2120
#define STR_ACK_FAULTS_QUESTION         2121
#define STR_WARNING                     2122
#define STR_INFORMATION                 2123
#define STR_FIND_SYMBOL                 2124
#define STR_NO_CORRESPONDING_SYMBOL     2125
#define STR_CNX_FILE_FILTER             2901
#define STR_CSV_FILE_FILTER             2904
#define STR_LOG_FILE_FILTER             2906
#define STR_PERTFILMS_LAYOUT_FILE_FILTER 2907
#define STR_PERTCONFIG_FILE_FILTER      2908
#define STR_BPB_DESC                    3000
#define STR_BPB_SYM_VIEW                3001
#define STR_BPB_CMD_READ_SYMBOL         3002
#define STR_BPB_CMD_WRITE_SYMBOL        3003
#define STR_BPB_CMD_WRITE_SYMBOL_HEXA   3004
#define STR_BPB_CMD_WRITE_SYMBOL_BIN    3005
#define STR_BPB_CMD_READ_IO             3006
#define STR_BPB_CMD_WRITE_IO            3007
#define STR_BPB_CMD_LOCK_IO             3008
#define STR_BPB_CMD_RELEASE_IO          3009
#define STR_BPB_CMD_READ_DEFAULT        3010
#define STR_BPB_CMD_LOCK_DEFAULT        3011
#define STR_BPB_CMD_RELEASE_DEFAULT     3012
#define STR_BPB_CMD_HEXADECIMAL_DISPLAY 3013
#define STR_BPB_CMD_DECIMAL_DISPLAY     3014
#define STR_BPB_CMD_SAVE_PARAM          3015
#define STR_BPB_CMD_RESTORE_PARAM       3016
#define STR_BPB_CMD_SAVE_PARAM_TO_FILE  3017
#define STR_BPB_CMD_EXEC_RPC            3018
#define STR_BPB_CMD_RD_CHANGE_MODE      3019
#define STR_BPB_CMD_RD_UPDATE_CLOCK     3020
#define STR_BPB_CMD_ACK_FAULTS          3021
#define STR_BPB_CMD_DUMP_SYMBOL         3022
#define STR_BPB_TYPE                    3030
#define STR_BPB_DESCRIPTION             3031
#define STR_BPB_SOFTWARE_VERSION        3032
#define STR_BPB_ENDIAN_TYPE             3033
#define STR_BPB_ENDIAN_TYPE_LITTLE      3034
#define STR_BPB_ENDIAN_TYPE_BIG         3035
#define STR_BPB_ADDR_BUS_WIDTH          3036
#define STR_BPB_DATA_MIN_WIDTH          3037
#define STR_BPB_UNKNOWN                 3038
#define STR_BPB_FILE_PREFIX             3039
#define STR_BPB_MAX_SYMBOLS_PER_DASHBOARD 3040
#define STR_BPB_SAVE_PARAM_FAILURE      3041
#define STR_BPB_RESTORE_PARAM_FAILURE   3042
#define STR_BPB_READ_FAILURE            3043
#define STR_BPB_WRITE_FAILURE           3044
#define STR_BPB_LOCK_FAILURE            3045
#define STR_BPB_RELEASE_FAILURE         3046
#define STR_BPB_EXEC_RPC_FAILURE        3047
#define STR_BPB_ACK_FAULTS_FAILURE      3048
#define STR_BPB_ACK_FAULTS_NOT_ALLOWED  3049
#define STR_BPB_RESULT                  3050
#define STR_BPB_PROC_VIEW               3051
#define STR_BPB_TITLE                   3052
#define STR_BPB_BUILD_DATE              3053
#define STR_BPB_COPY_NAME_TO_CLIPBOARD  3054
#define STR_BPB_ADD_TO_NEW_DASHBOARD    3055
#define STR_TRC_CMD_CLEAR_HISTORY       3089
#define STR_TRC_CMD_ACTIVATE_LOG_TO_FILE 3090
#define STR_TRC_CMD_DEACTIVATE_LOG_TO_FILE 3091
#define STR_TRC_CONSOLE                 3092
#define STR_TRC_LUA_OUTPUT              3093
#define STR_TRC_TITLE                   3094
#define STR_EVTDLG_EVENT_RECORDER       3100
#define STR_EVTDLG_CLEAR_EVENTS_FAILURE 3101
#define STR_EVTDLG_READ_EVENTS_FAILURE  3102
#define STR_EVTDLG_LOAD_EVENTSFILE_FAILURE 3103
#define STR_EVTDLG_APPEAR               3104
#define STR_EVTDLG_DISAPPEAR            3105
#define STR_EVTDLG_DISAPPEAR2           3105
#define STR_EVTDLG_FILTER_NONE          3107
#define STR_FILTER_NONE                 3108
#define STR_INITMEMSYMDLG_DOC_TITLE     3150
#define STR_INITMEMSYMDLG_LINE          3151
#define STR_INITMEMSYMDLG_ACTION        3152
#define STR_INITMEMSYMDLG_MEM_SYM       3153
#define STR_INITMEMSYMDLG_ERROR_UNKNOWM_COMMAND 3154
#define STR_INITMEMSYMDLG_STATUS_OK     3155
#define STR_INITMEMSYMDLG_ERROR_BAD_FORMAT 3156
#define STR_INITMEMSYMDLG_ERROR_BAD_ADDRESS 3157
#define STR_INITMEMSYMDLG_ERROR_BAD_WIDTH 3158
#define STR_INITMEMSYMDLG_WRITE_FAILURE 3159
#define STR_INITMEMSYMDLG_ACTION_WAIT   3160
#define STR_INITMEMSYMDLG_ERROR_BAD_WIDTH2 3161
#define STR_INITMEMSYMDLG_ERROR_INTERNAL 3161
#define STR_CLOCKDLG_UPDATE_FAILURE     3170
#define STR_CLOCKDLG_ERROR_BAD_YEAR     3171
#define STR_CLOCKDLG_NOT_ABSOLUTE       3172
#define STR_MODEDLG_READ_FAILURE        3180
#define STR_MODEDLG_WRITE_FAILURE       3181
#define STR_MEMDLG_DOC_TITLE            3200
#define STR_PROCMEMGRIDCTRL_READ_FAILURE 3250
#define STR_PROCMEMGRIDCTRL_WRITE_FAILURE 3251
#define STR_PROCMEMGRIDCTRL_ERROR_BAD_SIZE 3252
#define STR_PROCMEMGRIDCTRL_ERROR_NULL_SIZE 3253
#define STR_PROCMEMGRIDCTRL_ERROR_BAD_ADDRESS 3254
#define STR_PROCMEMGRIDCTRL_ERROR_BAD_VALUE 3255
#define STR_PROCMEMGRIDCTRL_ERROR_SIZE_TOO_BIG 3256
#define STR_CMD_REMOVE_SERIE            3300
#define STR_SCOPE_CMD_REMOVE_SERIE      3300
#define STR_PERTCTRLDLG_SNIFFER         3400
#define STR_PERTCTRLDLG_STOPPED         3401
#define STR_PERTCTRLDLG_ONWATCHED       3402
#define STR_PERTCTRLDLG_ARMED           3403
#define STR_PERTCTRLDLG_TRIGGERED       3404
#define STR_PERTCTRLDLG_INVALID_CFG     3405
#define STR_PERTCTRLDLG_USER_CFG        3406
#define STR_PERTCTRLDLG_FACTORY_CFG     3407
#define STR_PERTCTRLDLG_STOP_PERT_FAILURE 3410
#define STR_PERTCTRLDLG_ONWATCH_PERT_FAILURE 3411
#define STR_PERTCTRLDLG_ARM_PERT_FAILURE 3412
#define STR_PERTCTRLDLG_RESTORE_FACTORY_CFG_FAILURE 3413
#define STR_PERTCTRLDLG_UPLOAD_CFG_FAILURE 3414
#define STR_PERTCTRLDLG_DOWNLOAD_CFG_FAILURE 3415
#define STR_PERTCTRLDLG_DOWNLOAD_FILMS_FAILURE 3416
#define STR_PERTCTRLDLG_READING_VAR_NAMES_BUFFER 3417
#define STR_PERTCTRLDLG_READING_VAR_CHARACTERISTICS 3418
#define STR_PERTCTRLDLG_READING_FILMS   3419
#define STR_PERTCTRLDLG_READING_CONFIG  3420
#define STR_PERTCTRLDLG_WRITING_CONFIG  3421
#define STR_PERTCTRLDLG_DOWNLOAD_IN_PROGRESS 3422
#define STR_PERTFILMSDLG_ERROR_LOAD     3500
#define STR_PERTFILMSDLG_ERROR_NOT_FOUND_IN_FILM 3501
#define STR_OPERATOR_LEVEL              3550
#define STR_ENGINEER_LEVEL              3551
#define STR_ADMINISTRATOR_LEVEL         3552
#define STR_CONNECTED_STATE             3553
#define STR_PSEUDO_CONNECTED_STATE      3554
#define STR_DISCONNECTED_STATE          3555
#define STR_SEQTSTDLG_SEQ               3560
#define STR_STEP_NUM                    3561
#define STR_SEQTSTDLG_STOPPED           3562
#define STR_SEQTSTDLG_STOPPED_ON_ERROR  3563
#define STR_SEQTSTDLG_BUSY              3564
#define STR_SEQTSTDLG_PAUSED            3565
#define STR_SEQTSTDLG_START_FAILURE     3566
#define STR_SEQTSTDLG_STOP_FAILURE      3567
#define STR_SEQTSTDLG_CONTINUE_FAILURE  3568
#define STR_SEQTSTDLG_SET_STEP_BY_STEP_FAILURE 3569
#define STR_SEQTSTDLG_LOAD_TRACESFILE_FAILURE 3570
#define STR_QUESTION_DATA_INCOMPATIBLE  3571
#define STR_SAME_SW                     3572
#define STR_YES                         3573
#define STR_NO                          3574
#define STR_IN                          3575
#define STR_OUT                         3576
#define STR_UNKNOWN                     3577
#define STR_QUESTION_SAVE_DATA          3578
#define STR_SIZE                        3600
#define STR_CRC                         3601
#define STR_FILEMGRDLG_FILE_MANAGER     3602
#define STR_FILEMGRDLG_LIST_DIR_FAILURE 3603
#define STR_FILEMGRDLG_PUT_FILE_FAILURE 3604
#define STR_FILEMGRDLG_GET_FILE_FAILURE 3605
#define STR_FILEMGRDLG_DELETE_FILE_FAILURE 3606
#define STR_FILEMGRDLG_CREATE_DIR_FAILURE 3607
#define STR_FILEMGRDLG_DELETE_DIR_FAILURE 3608
#define STR_FILEMGRDLG_DIR_NAME_TO_CREATE 3609
#define STR_FILEMGRDLG_DELETE_QUESTION  3610
#define STR_FILEMGRDLG_DELETE_FILE_WARNING 3611
#define STR_FILEMGRDLG_DELETE_DIR_WARNING 3612
#define STR_FILEMGRDLG_CLOSING_FILE     3613
#define STR_LINE_NUMBER                 3614
#define STR_SPYDLG_SPY_RECORDER         3650
#define STR_SPYDLG_LOAD_SPYFILE_FAILURE 3651
#define ID_USER_CMD_BASE                12000
#define ID_VIEW_TRACE                   12770
#define ID_VIEW_PROCESSOREXPLORER       12771
#define ID_CONNECT                      12772
#define ID_PSEUDO_CONNECT               12773
#define ID_DISCONNECT                   12774
#define ID_NEW_CONNECTION_FILE          12775
#define ID_NEW_DASHBOARD                12776
#define ID_OPEN_DASHBOARD               12777
#define ID_OPEN_HTML                    12778
#define ID_OPEN_DASHBOARD_RECORDS       12779
#define ID_EVT_RECORDER                 12782
#define ID_MEM_WATCH                    12783
#define ID_NEW_INITIALIZER              12784
#define ID_RD_CHANGE_MODE               12785
#define ID_RD_UPDATE_CLOCK              12786
#define ID_ACK_FAULTS                   12787
#define ID_LUASCRIPT_NEWSCRIPT          12788
#define ID_LUASCRIPT_OPENSCRIPT         12789
#define ID_NEW_LUASCRIPT                12790
#define ID_OPENSCRIPT                   12791
#define ID_OPEN_LUASCRIPT               12792
#define ID_PERTURBOGRAPHE               12793
#define ID_OPEN_PERTURBOGRAPHE_FILMS    12794
#define ID_NEW_PERTURBOGRAPHE_CFG       12795
#define ID_SEQ_TST                      12796
#define ID_SEQ_TST_OPEN_FILE            12797
#define ID_EVT_RECORDER_OPEN_FILE       12798
#define ID_OPEN_PERTURBOGRAPHE_CFG      12799
#define ID_TOOLS_LANGUAGE               12800
#define ID_OUTILS_LANGUE                12801
#define ID_OUTILS_SPY                   12801
#define ID_FILE_MGR                     12802
#define ID_SPY_OUVRIRUNFICHIERSPY       12803
#define ID_SPY_RECORDER                 12804
#define ID_SPY_RECORDER_OPEN_FILE       12805
#define ID_TOOLS_SPY                    12806
#define ID_SPY_SPYRECORDER              12807
#define ID_Menu                         12808
#define ID_SPY_OPENASPYFILE             12809
#define ID_INDICATOR_CURR_MODE          12900
#define ID_INDICATOR_USER_LEVEL         12901
#define ID_INDICATOR_CONNECTION_STATE   12902
#define IDP_ALLOW_MODIFY_READONLY_FILE  12903
#define IDS_LINE_INDICATOR              12904
#define IDS_STYLE_INDICATOR             12905
#define IDS_FOLD_INDICATOR              12906
#define STR_ERROR_CTX_SIZE              12907
#define STR_POTENTIAL_ERROR_DATA        12908
#define ID_APP_RELEASE_NOTES            13000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         13001
#define _APS_NEXT_CONTROL_VALUE         1704
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
